### PR TITLE
Language: FI 

### PR DESCRIPTION
**Pull request by adafcaefc**
#2 re-opened after it got accidentally closed when cleaning the commits.
Original PR by @CodeBoi00

### CODE REVIEW

**Comment by adafcaefc** [comment]
I am waiting for Alizer to add the language in the application itself.

**Comment by AlizerUncaged** [comment]
images - 2021-08-05T023549 579

**Comment by AlizerUncaged** [comment]
man-waking-up-morning-stretching-yawning-bed-copy-space-man-waking-up-morning-stretching-yawning-137414640

**Pull request merged**
